Repository nipreps/fmriprep, pull requests merged in 2025-08, with the labels that each got.

#3512 FIX: Write out Freesurfer-derived outputs
  .circleci/ds005_fasttrack_outputs.txt
  .circleci/ds005_outputs.txt
  .circleci/ds005_partial_fasttrack_outputs.txt
  .circleci/ds005_partial_outputs.txt
  fmriprep/workflows/base.py
Labels: bug

#3506 DOC: Add myself to contributor list
  .maint/CONTRIBUTORS.md
Labels: documentation

#3504 DOC: Document `freesurfer` parameter in BOLD confound workflow init
  fmriprep/workflows/bold/confounds.py
Labels: documentation

#3513 ENH: Write out goodvoxels mask
  .circleci/ds005_partial_fasttrack_outputs.txt
  .circleci/ds005_partial_outputs.txt
  fmriprep/workflows/bold/base.py
Labels: CIFTI / Grayordinates
